-- ARCHIVO DEPURADO: FARMACIABD SOLO CON ESTRUCTURA Y USUARIO.

-- ===========================================
-- BLOQUE 01: ELIMINACIÓN Y CREACIÓN DE BASE Y USUARIO
-- ===========================================

DROP DATABASE IF EXISTS FARMACIABD;
DROP USER IF EXISTS 'usuario_farmacia'@'%';

CREATE DATABASE FARMACIABD;
CREATE USER 'usuario_farmacia'@'%' IDENTIFIED BY 'ClaveFarmacia123.';
GRANT ALL PRIVILEGES ON FARMACIABD.* TO 'usuario_farmacia'@'%';

-- ===========================================
-- BLOQUE 02: USO DE LA BASE DE DATOS
-- ===========================================
USE FARMACIABD;

-- ===========================================
-- BLOQUE 03: TABLA GENERAL DE ESTADOS
-- ===========================================
CREATE TABLE FIDE_ESTADO_TB (
    ID_ESTADO    INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION  VARCHAR(100) NOT NULL
);

-- ===========================================
-- BLOQUE 04: TABLAS DE USUARIOS Y ROLES
-- ===========================================
CREATE TABLE USUARIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    USUARIO VARCHAR(50) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(100) NOT NULL
);

CREATE TABLE ROL (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO_ROL (
    USUARIO_ID BIGINT,
    ROL_ID BIGINT,
    PRIMARY KEY (USUARIO_ID, ROL_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ID) ON DELETE CASCADE
);

CREATE TABLE CLIENTE (
    ID_CLIENTE BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO BIGINT NOT NULL,
    CEDULA VARCHAR(20),
    TELEFONO VARCHAR(20),
    DIRECCION VARCHAR(255),
    FECHA_NACIMIENTO DATE,
    SEXO VARCHAR(10),
    ALERGIAS TEXT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

-- ===========================================
-- BLOQUE 05: TABLAS DE LA RAMA INVENTARIO
-- ===========================================
CREATE TABLE FIDE_UNIDAD_MEDIDA_TB (
    ID_UNIDAD_MEDIDA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE           VARCHAR(50) NOT NULL,
    ID_ESTADO        INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

CREATE TABLE FIDE_CATEGORIA_PRODUCTO_TB (
    ID_CATEGORIA_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE                VARCHAR(100) NOT NULL,
    ID_ESTADO             INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

CREATE TABLE FIDE_PRODUCTO_TB (
    ID_PRODUCTO           INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE                VARCHAR(100) NOT NULL,
    CODIGO                VARCHAR(20) UNIQUE NOT NULL,
    PRECIO_UNITARIO       DECIMAL(10,2),
    ID_CATEGORIA_PRODUCTO INT,
    ID_UNIDAD_MEDIDA      INT,
    ID_ESTADO             INT,
    FOREIGN KEY (ID_CATEGORIA_PRODUCTO) REFERENCES FIDE_CATEGORIA_PRODUCTO_TB(ID_CATEGORIA_PRODUCTO),
    FOREIGN KEY (ID_UNIDAD_MEDIDA) REFERENCES FIDE_UNIDAD_MEDIDA_TB(ID_UNIDAD_MEDIDA),
    FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

CREATE TABLE FIDE_LOTE_TB (
    ID_LOTE           INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO       INT,
    NUMERO_LOTE       VARCHAR(100),
    FECHA_ELABORADO   DATE,
    FECHA_VENCIMIENTO DATE,
    ID_ESTADO         INT,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO),
    FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

CREATE TABLE FIDE_FARMACIA_TB (
    ID_FARMACIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE      VARCHAR(100) NOT NULL,
    ID_ESTADO   INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

CREATE TABLE FIDE_INVENTARIO_TB (
    ID_INVENTARIO       INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO         INT,
    CANTIDAD_DISPONIBLE INT NOT NULL,
    STOCK_MINIMO        INT,
    STOCK_MAXIMO        INT,
    ID_FARMACIA         INT,
    ID_ESTADO           INT,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO),
    FOREIGN KEY (ID_FARMACIA) REFERENCES FIDE_FARMACIA_TB(ID_FARMACIA),
    FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

CREATE TABLE TIPO_ALERTA (
    ID_TIPO_ALERTA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE         VARCHAR(100) NOT NULL,
    ID_ESTADO      INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);

CREATE TABLE FIDE_ALERTA_TB (
    ID_ALERTA      INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_ALERTA   DATE NOT NULL,
    ID_TIPO_ALERTA INT,
    ID_INVENTARIO  INT,
    ID_ESTADO      INT,
    FOREIGN KEY (ID_TIPO_ALERTA) REFERENCES TIPO_ALERTA(ID_TIPO_ALERTA),
    FOREIGN KEY (ID_INVENTARIO) REFERENCES FIDE_INVENTARIO_TB(ID_INVENTARIO),
    FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);


-- ===========================================
-- BLOQUE 06: TABLA DE REGISTRO DE ERRORES
-- ===========================================
CREATE TABLE TERROR (
    ID_ERROR   INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION TEXT NOT NULL,
    FECHAHORA DATETIME NOT NULL
);


-- FIN DEL SCRIPT DE ESTRUCTURA



















